### ISSUE TITLE
bug: Error in WriteThumbnail (--write-thumbnail) function accepting parameter in yt-dlp

### ISSUE THREAD

**Issue by eos175** [lrstanley/go-ytdlp#26]
### 🌧 Describe the problem

The `WriteThumbnail` function in the current yt-dlp codebase is defined to accept a parameter, which does not align with the project's specification. In yt-dlp, this function should be defined without parameters, causing an error during execution.

**Additional Note:**
Additionally, I have introduced a progress bar functionality that may be interesting to add to the project. You can view it [here](https://github.com/eos175/go-ytdlp/commit/8eb98f3a3b4af4d47306589303402654cd00c859) 

### ⛅ Expected behavior

```
func (c *Command) WriteThumbnail() *Command
```

### 🔄 Minimal reproduction

```
dl := ytdlp.New().
		PrintJSON().
		WriteThumbnail("").
		...
		
```

### 💠 Version: go-ytdlp

2024.07.09

### 🖥 Version: Operating system

linux/other

### 🤝 Requirements

- [X] I believe the problem I'm facing is a bug, and is not intended behavior. [Post here if you're not sure](../discussions/new?category=q-a).
- [X] I have confirmed that someone else has not [submitted a similar bug report](../labels/bug).

**Comment by lrstanley** [comment]
Looks like this is caused by the cli flag parsing library which ytdlp uses saying that some of the flags accept a certain number of arguments when they in fact don't. may be a bug in the upstream (not yt-dlp itself). Pushing up a fix shortly.
